# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05354b0fb68f26cebd819884b865700a2672338c899f5044954a8c45316001785e557c54b1c8dfa6ad2f37ef7afccd50429f87dc536e62be7d4a86433206295a

test:
  secret_key_base: 84e29fb9aa0d1006c2e9b45a2985f8d10208c8e6cb6936e4930b857b6ec3de4b88b7f3d6b38f99b1d889be00c5b580f892f50d5c80e4f1ed59528433e20481c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
